version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always

  books_api:
    image: book-api:1.0
    ports:
      - 8080:8080
    restart: always

    depends_on:
      - mongodb